/*
 Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){function l(a){var c=a.widgets,b=a.focusManager.currentActive;if(a.focusManager.hasFocus){if(c.focused)return c.focused;if(b instanceof CKEDITOR.plugins.widget.nestedEditable)return c.getByElement(b)}}function m(a,c){return a.features&&-1!==CKEDITOR.tools.array.indexOf(a.features,c)}function p(a,c){return CKEDITOR.tools.array.reduce(CKEDITOR.tools.objectKeys(a),function(b,e){var d=a[e];m(d,c)&&b.push(d);return b},[])}function t(a,c){c=CKEDITOR.tools.object.merge({pathName:a.lang.imagebase.pathName,
defaults:{imageClass:a.config.easyimage_class||"",alt:"",src:"",caption:""},template:'\x3cfigure class\x3d"{imageClass}"\x3e\x3cimg alt\x3d"{alt}" src\x3d"{src}" /\x3e\x3cfigcaption\x3e{caption}\x3c/figcaption\x3e\x3c/figure\x3e',allowedContent:{img:{attributes:"!src,alt,width,height"},figure:!0,figcaption:!0},requiredContent:"figure; img[!src]",features:[],editables:{caption:{selector:"figcaption",pathName:a.lang.imagebase.pathNameCaption,allowedContent:"br"}},parts:{image:"img",caption:"figcaption"},
upcasts:{figure:function(a){if(1===a.find("img",!0).length)return a}}},c);c.upcast=CKEDITOR.tools.objectKeys(c.upcasts).join(",");return c}function k(a){this.wrapper=CKEDITOR.dom.element.createFromHtml(a||'\x3cdiv class\x3d"cke_loader"\x3e\x3c/div\x3e')}function n(){k.call(this,'\x3cdiv class\x3d"cke_loader"\x3e\x3cdiv class\x3d"cke_bar" styles\x3d"transition: width '+q/1E3+'s"\x3e\x3c/div\x3e\x3c/div\x3e');this.bar=this.wrapper.getFirst()}var r=!1,u={caption:function(){function a(a){a.parts.caption.data("cke-caption-placeholder",
a.editor.lang.imagebase.captionPlaceholder)}return{setUp:function(a){function b(d){var b=(d="blur"===d.name?a.elementPath():d.data.path)?d.lastElement:null;d=p(a.widgets.instances,"caption");if(!a.filter.check("figcaption"))return CKEDITOR.tools.array.forEach(e,function(a){a.removeListener()});CKEDITOR.tools.array.forEach(d,function(a){a._refreshCaption(b)})}var e=[];e.push(a.on("selectionChange",b,null,null,9));e.push(a.on("blur",b));e.push(a.on("key",function(d){var b=p(a.widgets.instances,"caption");
CKEDITOR.tools.array.forEach(b,function(a){if(l(a.editor)===a)return 13==d.data.keyCode&&d.cancel(),!1})},null,null,100));e.push(a.on("paste",function(d){var b=p(a.widgets.instances,"caption");CKEDITOR.tools.array.forEach(b,function(a){if(l(a.editor)===a)return d.data.dataValue=d.data.dataValue.replace(/<.*?>/ig,""),!1})},null,null,100))},init:function(){if(this.editor.filter.check("figcaption")){if(!this.parts.caption){var a=this.parts,b=this.element,e=b.getDocument().createElement("figcaption");
b.append(e);this.initEditable("caption",this.definition.editables.caption);a.caption=e}this.editables.caption.getData()||this.parts.caption.data("cke-caption-placeholder")||this._refreshCaption()}},_refreshCaption:function(c){var b=l(this.editor)===this,e=this.parts.caption,d=this.editables.caption;b?d.getData()||c.equals(e)?(!c||c.equals(e)&&c.data("cke-caption-placeholder"))&&this.parts.caption.data("cke-caption-placeholder",!1):a(this):a(this)}}}(),upload:function(){return{progressReporterType:n,
setUp:function(a,c){a.on("paste",function(a){})},init:function(){this.once("ready",function(){})},_isLoaderDone:function(a){return a.xhr&&4===a.xhr.readyState},_spawnLoader:function(a,c,b,e){var d=b.loadMethod||"loadAndUpload";a=a.uploadRepository.create(c,e,b.loaderType);a[d](b.uploadUrl,b.additionalRequestParameters);return a},_beginUpload:function(a,c){function b(){a.isInited()&&a.setData("uploadId",void 0);a.wrapper.removeClass("cke_widget_wrapper_uploading")}function e(){b();!1!==a.fire("uploadFailed",
{loader:c})&&a.editor.widgets.del(a)}var d={uploaded:function(){b();a.fire("uploadDone",{loader:c})},abort:e,error:e},g=[];g.push(c.on("abort",d.abort));g.push(c.on("error",d.error));g.push(c.on("uploaded",d.uploaded));this.on("destroy",function(){CKEDITOR.tools.array.filter(g,function(a){a.removeListener();return!1})});a.setData("uploadId",c.id);if(!1!==a.fire("uploadStarted",c)&&a.progressReporterType)if(!a._isLoaderDone(c))a.wrapper.addClass("cke_widget_wrapper_uploading"),d=new a.progressReporterType,
a.wrapper.append(d.wrapper),d.bindLoader(c);else if(d[c.status])d[c.status]()},_insertWidget:function(a,c,b,e,d){var g=("function"==typeof c.defaults?c.defaults():c.defaults)||{},g=CKEDITOR.tools.extend({},g);g.src=b;b=CKEDITOR.dom.element.createFromHtml(c.template.output(g));var g=a.widgets.wrapElement(b,c.name),f=new CKEDITOR.dom.documentFragment(g.getDocument());f.append(g);return!1!==e?(a.widgets.initOn(b,c,d),a.widgets.finalizeCreation(f)):b}}}(),link:function(){function a(a){a.addMenuGroup("imagebase",
10);a.addMenuItem("imagebase",{label:a.lang.link.menu,command:"link",group:"imagebase"})}function c(a,d,b){return function(){if(b&&m(b,"link")){a.stop();var c={};d.commitContent(c);b.setData("link",c)}}}function b(a,d,b){a.getCommand("unlink").on(d,function(d){var c=l(a);c&&m(c,"link")&&(d.stop(),b&&"function"===typeof b&&b(this,c,a),d.cancel())})}return{allowedContent:{a:{attributes:"!href"}},parts:{link:"a"},init:function(){if(this.editor.plugins.link&&this.editor.contextMenu)this.on("contextMenu",
function(a){this.parts.link&&(a.data.link=a.data.unlink=CKEDITOR.TRISTATE_OFF)})},setUp:function(e){e.plugins.link&&(e.contextMenu&&a(e),e.on("dialogShow",function(a){var b=l(e),f=a.data,h,k;b&&m(b,"link")&&"link"===f._.name&&(h=f.getContentElement("info","linkDisplayText").getElement().getParent().getParent(),f.setupContent(b.data.link||{}),h.hide(),k=f.once("ok",c(a,f,b),null,null,9),f.once("hide",function(){k.removeListener();h.show()}))}),b(e,"exec",function(a,b,c){b.setData("link",null);a.refresh(c,
c.elementPath())}),b(e,"refresh",function(a,b){a.setState(b.parts.link?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED)}))},data:function(a){var b=this.editor,c=a.data.link,f=this.element.findOne("img");"undefined"===typeof c&&this.parts.link&&this.setData("link",CKEDITOR.plugins.link.parseLinkAttributes(this.editor,this.parts.link));if("undefined"!==typeof c)if(null===c)this.parts.link.remove(!0),this.parts.link=null,delete a.data.link;else{a=this.parts;var h=f.getAscendant("a")||b.document.createElement("a"),
b=CKEDITOR.plugins.link.getLinkAttributes(b,c);CKEDITOR.tools.isEmpty(b.set)||h.setAttributes(b.set);b.removed.length&&h.removeAttributes(b.removed);h.contains(f)||(h.replace(f),f.move(h));a.link=h}}}}()},q=100;k.prototype={updated:function(){},done:function(){this.remove()},aborted:function(){this.remove()},failed:function(){this.remove()},remove:function(){this.wrapper.remove()},bindLoader:function(a){function c(){b&&(CKEDITOR.tools.array.forEach(b,function(a){a.removeListener()}),b=null)}var b=
[],e=CKEDITOR.tools.eventsBuffer(q,function(){a.uploadTotal&&this.updated(a.uploaded/a.uploadTotal)},this);b.push(a.on("update",e.input,this));b.push(a.once("abort",this.aborted,this));b.push(a.once("uploaded",this.done,this));b.push(a.once("error",this.failed,this));b.push(a.once("abort",c));b.push(a.once("uploaded",c));b.push(a.once("error",c))}};n.prototype=new k;n.prototype.updated=function(a){a=Math.round(100*a);a=Math.max(a,0);a=Math.min(a,100);this.bar.setStyle("width",a+"%")};CKEDITOR.plugins.add("imagebase",
{requires:"widget,filetools",lang:"en",init:function(a){r||(CKEDITOR.document.appendStyleSheet(this.path+"styles/imagebase.css"),r=!0);a.addContentsCss&&a.addContentsCss(this.path+"styles/imagebase.css")}});CKEDITOR.plugins.imagebase={featuresDefinitions:u,addImageWidget:function(a,c,b){c=a.widgets.add(c,t(a,b));a.addFeature(c)},addFeature:function(a,c,b){function e(a,b){if(a||b)return function(){a&&a.apply(this,arguments);b&&b.apply(this,arguments)}}var d=CKEDITOR.tools.clone(this.featuresDefinitions[c]);
d.init=e(b.init,d.init);d.data=e(b.data,d.data);d.setUp&&(d.setUp(a,b),delete d.setUp);a=CKEDITOR.tools.object.merge(b,d);CKEDITOR.tools.isArray(a.features)||(a.features=[]);a.features.push(c);return a},progressBar:n,progressReporter:k}})();