/*
 Copyright (c) 2003-2018, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
(function(){function l(a){var b=a.widgets,c=a.focusManager.currentActive;if(a.focusManager.hasFocus){if(b.focused)return b.focused;if(c instanceof CKEDITOR.plugins.widget.nestedEditable)return b.getByElement(c)}}function m(a,b){return a.features&&-1!==CKEDITOR.tools.array.indexOf(a.features,b)}function p(a,b){return CKEDITOR.tools.array.reduce(CKEDITOR.tools.objectKeys(a),function(c,e){var d=a[e];m(d,b)&&c.push(d);return c},[])}function t(a,b){b=CKEDITOR.tools.object.merge({pathName:a.lang.imagebase.pathName,
defaults:{imageClass:a.config.easyimage_class||"",alt:"",src:"",caption:""},template:'\x3cfigure class\x3d"{imageClass}"\x3e\x3cimg alt\x3d"{alt}" src\x3d"{src}" /\x3e\x3cfigcaption\x3e{caption}\x3c/figcaption\x3e\x3c/figure\x3e',allowedContent:{img:{attributes:"!src,alt,width,height"},figure:!0,figcaption:!0},requiredContent:"figure; img[!src]",features:[],editables:{caption:{selector:"figcaption",pathName:a.lang.imagebase.pathNameCaption,allowedContent:"br"}},parts:{image:"img",caption:"figcaption"},
upcasts:{figure:function(a){if(1===a.find("img",!0).length)return a}}},b);b.upcast=CKEDITOR.tools.objectKeys(b.upcasts).join(",");return b}function k(a){this.wrapper=CKEDITOR.dom.element.createFromHtml(a||'\x3cdiv class\x3d"cke_loader"\x3e\x3c/div\x3e')}function n(){k.call(this,'\x3cdiv class\x3d"cke_loader"\x3e\x3cdiv class\x3d"cke_bar" styles\x3d"transition: width '+q/1E3+'s"\x3e\x3c/div\x3e\x3c/div\x3e');this.bar=this.wrapper.getFirst()}var r=!1,u={caption:function(){function a(a){a.parts.caption.data("cke-caption-placeholder",
!1)}function b(a,b){a.data("cke-caption-active",b);a.data("cke-caption-hidden",!b);b?a.removeClass("no-content"):a.addClass("no-content")}return{setUp:function(a){function b(f){var e=(f="blur"===f.name?a.elementPath():f.data.path)?f.lastElement:null;f=p(a.widgets.instances,"caption");if(!a.filter.check("figcaption"))return CKEDITOR.tools.array.forEach(d,function(a){a.removeListener()});CKEDITOR.tools.array.forEach(f,function(a){a._refreshCaption(e)})}var d=[];d.push(a.on("selectionChange",b,null,
null,9));d.push(a.on("blur",b));d.push(a.on("key",function(d){var b=p(a.widgets.instances,"caption");CKEDITOR.tools.array.forEach(b,function(a){if(l(a.editor)===a)return 13==d.data.keyCode&&d.cancel(),!1})},null,null,100));d.push(a.on("paste",function(d){var b=p(a.widgets.instances,"caption");CKEDITOR.tools.array.forEach(b,function(a){if(l(a.editor)===a)return d.data.dataValue=d.data.dataValue.replace(/<.*?>/ig,""),!1})},null,null,100))},init:function(){if(this.editor.filter.check("figcaption")){if(!this.parts.caption){var a=
this.parts,b=this.element,d=b.getDocument().createElement("figcaption");b.append(d);this.initEditable("caption",this.definition.editables.caption);a.caption=d}this.editables.caption.getData()||this.parts.caption.data("cke-caption-placeholder")||this._refreshCaption()}},_refreshCaption:function(c){var e=l(this.editor)===this,d=this.parts.caption,f=this.editables.caption;if(e)f.getData()||c.equals(d)?(!c||c.equals(d)&&c.data("cke-caption-placeholder"))&&a(this):this.parts.caption.data("cke-caption-placeholder",
this.editor.lang.imagebase.captionPlaceholder),b(d,!0);else if(!this.editables.caption.getData()||this.parts.caption.data("cke-caption-placeholder"))a(this),b(d,!1)}}}(),upload:function(){return{progressReporterType:n,setUp:function(a,b){a.on("paste",function(a){})},init:function(){this.once("ready",function(){})},_isLoaderDone:function(a){return a.xhr&&4===a.xhr.readyState},_spawnLoader:function(a,b,c,e){var d=c.loadMethod||"loadAndUpload";a=a.uploadRepository.create(b,e,c.loaderType);a[d](c.uploadUrl,
c.additionalRequestParameters);return a},_beginUpload:function(a,b){function c(){a.isInited()&&a.setData("uploadId",void 0);a.wrapper.removeClass("cke_widget_wrapper_uploading")}function e(){c();!1!==a.fire("uploadFailed",{loader:b})&&a.editor.widgets.del(a)}var d={uploaded:function(){c();a.fire("uploadDone",{loader:b})},abort:e,error:e},f=[];f.push(b.on("abort",d.abort));f.push(b.on("error",d.error));f.push(b.on("uploaded",d.uploaded));this.on("destroy",function(){CKEDITOR.tools.array.filter(f,function(a){a.removeListener();
return!1})});a.setData("uploadId",b.id);if(!1!==a.fire("uploadStarted",b)&&a.progressReporterType)if(!a._isLoaderDone(b))a.wrapper.addClass("cke_widget_wrapper_uploading"),d=new a.progressReporterType,a.wrapper.append(d.wrapper),d.bindLoader(b);else if(d[b.status])d[b.status]()},_insertWidget:function(a,b,c,e,d){var f=("function"==typeof b.defaults?b.defaults():b.defaults)||{},f=CKEDITOR.tools.extend({},f);f.src=c;c=CKEDITOR.dom.element.createFromHtml(b.template.output(f));var f=a.widgets.wrapElement(c,
b.name),g=new CKEDITOR.dom.documentFragment(f.getDocument());g.append(f);return!1!==e?(a.widgets.initOn(c,b,d),a.widgets.finalizeCreation(g)):c}}}(),link:function(){function a(a){a.addMenuGroup("imagebase",10);a.addMenuItem("imagebase",{label:a.lang.link.menu,command:"link",group:"imagebase"})}function b(a,b,f){return function(){if(f&&m(f,"link")){a.stop();var c={};b.commitContent(c);f.setData("link",c)}}}function c(a,b,c){a.getCommand("unlink").on(b,function(b){var d=l(a);d&&m(d,"link")&&(b.stop(),
c&&"function"===typeof c&&c(this,d,a),b.cancel())})}return{allowedContent:{a:{attributes:"!href"}},parts:{link:"a"},init:function(){if(this.editor.plugins.link&&this.editor.contextMenu)this.on("contextMenu",function(a){this.parts.link&&(a.data.link=a.data.unlink=CKEDITOR.TRISTATE_OFF)})},setUp:function(e){e.plugins.link&&(e.contextMenu&&a(e),e.on("dialogShow",function(a){var c=l(e),g=a.data,h,k;c&&m(c,"link")&&"link"===g._.name&&(h=g.getContentElement("info","linkDisplayText").getElement().getParent().getParent(),
g.setupContent(c.data.link||{}),h.hide(),k=g.once("ok",b(a,g,c),null,null,9),g.once("hide",function(){k.removeListener();h.show()}))}),c(e,"exec",function(a,b,c){b.setData("link",null);a.refresh(c,c.elementPath())}),c(e,"refresh",function(a,b){a.setState(b.parts.link?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED)}))},data:function(a){var b=this.editor,c=a.data.link,g=this.element.findOne("img");"undefined"===typeof c&&this.parts.link&&this.setData("link",CKEDITOR.plugins.link.parseLinkAttributes(this.editor,
this.parts.link));if("undefined"!==typeof c)if(null===c)this.parts.link.remove(!0),this.parts.link=null,delete a.data.link;else{a=this.parts;var h=g.getAscendant("a")||b.document.createElement("a"),b=CKEDITOR.plugins.link.getLinkAttributes(b,c);CKEDITOR.tools.isEmpty(b.set)||h.setAttributes(b.set);b.removed.length&&h.removeAttributes(b.removed);h.contains(g)||(h.replace(g),g.move(h));a.link=h}}}}()},q=100;k.prototype={updated:function(){},done:function(){this.remove()},aborted:function(){this.remove()},
failed:function(){this.remove()},remove:function(){this.wrapper.remove()},bindLoader:function(a){function b(){c&&(CKEDITOR.tools.array.forEach(c,function(a){a.removeListener()}),c=null)}var c=[],e=CKEDITOR.tools.eventsBuffer(q,function(){a.uploadTotal&&this.updated(a.uploaded/a.uploadTotal)},this);c.push(a.on("update",e.input,this));c.push(a.once("abort",this.aborted,this));c.push(a.once("uploaded",this.done,this));c.push(a.once("error",this.failed,this));c.push(a.once("abort",b));c.push(a.once("uploaded",
b));c.push(a.once("error",b))}};n.prototype=new k;n.prototype.updated=function(a){a=Math.round(100*a);a=Math.max(a,0);a=Math.min(a,100);this.bar.setStyle("width",a+"%")};CKEDITOR.plugins.add("imagebase",{requires:"widget,filetools",lang:"en",init:function(a){r||(CKEDITOR.document.appendStyleSheet(this.path+"styles/imagebase.css"),r=!0);a.addContentsCss&&a.addContentsCss(this.path+"styles/imagebase.css")}});CKEDITOR.plugins.imagebase={featuresDefinitions:u,addImageWidget:function(a,b,c){b=a.widgets.add(b,
t(a,c));a.addFeature(b)},addFeature:function(a,b,c){function e(a,b){if(a||b)return function(){a&&a.apply(this,arguments);b&&b.apply(this,arguments)}}var d=CKEDITOR.tools.clone(this.featuresDefinitions[b]);d.init=e(c.init,d.init);d.data=e(c.data,d.data);d.setUp&&(d.setUp(a,c),delete d.setUp);a=CKEDITOR.tools.object.merge(c,d);CKEDITOR.tools.isArray(a.features)||(a.features=[]);a.features.push(b);return a},progressBar:n,progressReporter:k}})();